### PR TITLE
Use render instead of createApp when rendering vdom

### PR DESCRIPTION
**Pull request by larrifax**
When rendering Vue components inside of `<template #eventContent></template>`, the Vue components aren't rendered within the main Vue application's context, but in a new Vue application created by the following function:
https://github.com/fullcalendar/fullcalendar-vue/blob/d203b0c693b08a62cccdeb47a38fc609d41205ed/src/custom-content-type.ts#L57-L76

Since the new Vue application isn't connected to the main Vue application in any way, information about e.g. plugins are lost, making it impossible to use e.g. `vue-i18n-next` within the rendered components.

I've found a way to overcome this limitation, by patching the library to use `render()` instead of `createApp()`, but I'm by no means a Vue expert so I don't know if this is a viable approach or not.

The work is inspired by https://github.com/vuejs/core/issues/2097#issuecomment-707975628 and some of the other comments in the same thread.

### CODE REVIEW

**Comment by acerix** [comment]
Please submit the feature request under Issues, then link this PR to it.

**Comment by TheNoim** [comment]
Thanks, this is a big performance issue for me.

**Comment by keygun-development** [comment]
This is also a big preformance issue for me, I've just created an issue for this.

**Comment by sebastienfontaine** [comment]
Please, this is also a big performance issue for me.

**Comment by arshaw** [comment]
I've recently fixed this performance issue, though via a different technique. I'm using [Teleport](https://vuejs.org/guide/built-ins/teleport.html) instead.

See my comment:
https://github.com/fullcalendar/fullcalendar-vue/issues/191#issuecomment-1335796314

@larrifax , thank you for the effort you put into this

**Pull request closed without merging**
